server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/identity_service}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_PASSWORD:root}
    password: ${DBMS_USERNAME:}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  SIGNER_KEY: LwlIyPF9LMGrTWkRVcw++jZDhJL6c42HQV1pCsXMKw0+/OSz9lRHuhR6ZLPOcKKO
  valid-duration: 3600
  refreshable-duration: 7200

outbound:
  client-id: ${DBMS_CLIENTID}
  client-secret: ${DBMS_CLIENTSECRET}
  redirect-uri: http://localhost:3000/authenticate
  grant-type: authorization_code
